# Generated by Django 3.2 on 2022-12-20 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nomes')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='Cpf')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='data de registro')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cvitae', models.ImageField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
            ],
        ),
    ]
